java -jar jscompiler.jar --js ./src/history/historyL.js --js_output_file ./src_rel/history/historyL.js
java -jar jscompiler.jar --js ./src/include/left.js --js_output_file ./src_rel/include/left.js
java -jar jscompiler.jar --js ./src/include/top.js --js_output_file ./src_rel/include/top.js
java -jar jscompiler.jar --js ./src/main/main.js --js_output_file ./src_rel/main/main.js
java -jar jscompiler.jar --js ./src/manage/login/forgetform.js --js_output_file ./src_rel/manage/login/forgetform.js
java -jar jscompiler.jar --js ./src/manage/login/login.js --js_output_file ./src_rel/manage/login/login.js
java -jar jscompiler.jar --js ./src/manage/login/registerform.js --js_output_file ./src_rel/manage/login/registerform.js
java -jar jscompiler.jar --js ./src/manage/accountdetail.js --js_output_file ./src_rel/manage/accountdetail.js
java -jar jscompiler.jar --js ./src/manage/accountL.js --js_output_file ./src_rel/manage/accountL.js
java -jar jscompiler.jar --js ./src/manage/companyDetail.js --js_output_file ./src_rel/manage/companyDetail.js
java -jar jscompiler.jar --js ./src/manage/companyL.js --js_output_file ./src_rel/manage/companyL.js
java -jar jscompiler.jar --js ./src/manage/productD.js --js_output_file ./src_rel/manage/productD.js
java -jar jscompiler.jar --js ./src/manage/productTypeDetail.js --js_output_file ./src_rel/manage/productTypeDetail.js
java -jar jscompiler.jar --js ./src/manage/productTypeL.js --js_output_file ./src_rel/manage/productTypeL.js
java -jar jscompiler.jar --js ./src/manage/rolemodifyform.js --js_output_file ./src_rel/manage/rolemodifyform.js
java -jar jscompiler.jar --js ./src/notice/noticeD.js --js_output_file ./src_rel/notice/noticeD.js
java -jar jscompiler.jar --js ./src/notice/noticedetailview.js --js_output_file ./src_rel/notice/noticedetailview.js
java -jar jscompiler.jar --js ./src/notice/noticeL.js --js_output_file ./src_rel/notice/noticeL.js
java -jar jscompiler.jar --js ./src/product/productD.js --js_output_file ./src_rel/product/productD.js
java -jar jscompiler.jar --js ./src/product/productdetailview.js --js_output_file ./src_rel/product/productdetailview.js
java -jar jscompiler.jar --js ./src/product/productL.js --js_output_file ./src_rel/product/productL.js
java -jar jscompiler.jar --js ./src/qna/qnaD.js --js_output_file ./src_rel/qna/qnaD.js
java -jar jscompiler.jar --js ./src/qna/qnadetailview.js --js_output_file ./src_rel/qna/qnadetailview.js
java -jar jscompiler.jar --js ./src/qna/qnaL.js --js_output_file ./src_rel/qna/qnaL.js
java -jar jscompiler.jar --js ./src/guide/guideL.js --js_output_file ./src_rel/guide/guideL.js
java -jar jscompiler.jar --js ./src/util.js --js_output_file ./src_rel/util.js